// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Presupuesto.Infrastructure.Data;

#nullable disable

namespace Presupuesto.Infrastructure.Migrations
{
    [DbContext(typeof(PresupuestoDbContext))]
    [Migration("20260402213058_InitialSqlServerCreate")]
    partial class InitialSqlServerCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Presupuesto.Domain.Entities.CategoriaPresupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsSistema")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasPresupuesto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EsSistema = true,
                            Nombre = "Obligaciones"
                        },
                        new
                        {
                            Id = 2,
                            EsSistema = false,
                            Nombre = "Gastos Personales"
                        },
                        new
                        {
                            Id = 3,
                            EsSistema = false,
                            Nombre = "Metas y Ahorro"
                        },
                        new
                        {
                            Id = 4,
                            EsSistema = false,
                            Nombre = "Fondo de Apoyo"
                        },
                        new
                        {
                            Id = 5,
                            EsSistema = false,
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("Presupuesto.Domain.Entities.DistribucionPresupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Bloqueada")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaPresupuestoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PresupuestoMensualId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPresupuestoId");

                    b.HasIndex("PresupuestoMensualId");

                    b.ToTable("DistribucionesPresupuesto");
                });

            modelBuilder.Entity("Presupuesto.Domain.Entities.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaPresupuestoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SubCategoria")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPresupuestoId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("Presupuesto.Domain.Entities.PresupuestoMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PresupuestosMensuales");
                });

            modelBuilder.Entity("Presupuesto.Domain.Entities.SaldoPresupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaPresupuestoId")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PresupuestoMensualId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPresupuestoId");

                    b.HasIndex("PresupuestoMensualId");

                    b.ToTable("SaldosPresupuesto");
                });

            modelBuilder.Entity("Presupuesto.Domain.Entities.DistribucionPresupuesto", b =>
                {
                    b.HasOne("Presupuesto.Domain.Entities.CategoriaPresupuesto", "CategoriaPresupuesto")
                        .WithMany()
                        .HasForeignKey("CategoriaPresupuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Presupuesto.Domain.Entities.PresupuestoMensual", "PresupuestoMensual")
                        .WithMany("Distribuciones")
                        .HasForeignKey("PresupuestoMensualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaPresupuesto");

                    b.Navigation("PresupuestoMensual");
                });

            modelBuilder.Entity("Presupuesto.Domain.Entities.Gasto", b =>
                {
                    b.HasOne("Presupuesto.Domain.Entities.CategoriaPresupuesto", "CategoriaPresupuesto")
                        .WithMany()
                        .HasForeignKey("CategoriaPresupuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaPresupuesto");
                });

            modelBuilder.Entity("Presupuesto.Domain.Entities.SaldoPresupuesto", b =>
                {
                    b.HasOne("Presupuesto.Domain.Entities.CategoriaPresupuesto", "CategoriaPresupuesto")
                        .WithMany()
                        .HasForeignKey("CategoriaPresupuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Presupuesto.Domain.Entities.PresupuestoMensual", "PresupuestoMensual")
                        .WithMany("Saldos")
                        .HasForeignKey("PresupuestoMensualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaPresupuesto");

                    b.Navigation("PresupuestoMensual");
                });

            modelBuilder.Entity("Presupuesto.Domain.Entities.PresupuestoMensual", b =>
                {
                    b.Navigation("Distribuciones");

                    b.Navigation("Saldos");
                });
#pragma warning restore 612, 618
        }
    }
}
