// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Presupuesto.Infrastructure.Data;

#nullable disable

namespace Presupuesto.Infrastructure.Migrations
{
    [DbContext(typeof(PresupuestoDbContext))]
    partial class PresupuestoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Presupuesto.Domain.Entities.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gastos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = 1,
                            Descripcion = "Supermercado semanal",
                            Fecha = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 150.50m
                        },
                        new
                        {
                            Id = 2,
                            Categoria = 2,
                            Descripcion = "Gasolina",
                            Fecha = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 80.00m
                        },
                        new
                        {
                            Id = 3,
                            Categoria = 3,
                            Descripcion = "Factura de luz",
                            Fecha = new DateTime(2026, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 65.30m
                        },
                        new
                        {
                            Id = 4,
                            Categoria = 4,
                            Descripcion = "Cine y cena",
                            Fecha = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 45.00m
                        },
                        new
                        {
                            Id = 5,
                            Categoria = 1,
                            Descripcion = "Restaurante",
                            Fecha = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 32.50m
                        },
                        new
                        {
                            Id = 6,
                            Categoria = 3,
                            Descripcion = "Internet",
                            Fecha = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 55.00m
                        },
                        new
                        {
                            Id = 7,
                            Categoria = 5,
                            Descripcion = "Medicinas",
                            Fecha = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 28.75m
                        },
                        new
                        {
                            Id = 8,
                            Categoria = 1,
                            Descripcion = "Compras mensuales",
                            Fecha = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 200.00m
                        },
                        new
                        {
                            Id = 9,
                            Categoria = 2,
                            Descripcion = "Mantenimiento auto",
                            Fecha = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 120.00m
                        },
                        new
                        {
                            Id = 10,
                            Categoria = 4,
                            Descripcion = "Concierto",
                            Fecha = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 75.00m
                        },
                        new
                        {
                            Id = 11,
                            Categoria = 3,
                            Descripcion = "Agua y gas",
                            Fecha = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 48.50m
                        },
                        new
                        {
                            Id = 12,
                            Categoria = 5,
                            Descripcion = "Regalos",
                            Fecha = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 60.00m
                        });
                });

            modelBuilder.Entity("Presupuesto.Domain.Entities.PresupuestoMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PresupuestosMensuales");
                });
#pragma warning restore 612, 618
        }
    }
}
